openapi: 3.0.4
info:
  version: '1.0'
  title: "Tap-on-places OpenAPI 3.0"
  description: API per i turisti per trovare le attività di Trento.
  license:
    name: MIT
/*servers:
  - url: http://localhost:8080/api/v1
    description: Localhost
  - url: https://easy-lib.onrender.com/api/v1
    description: render.com
    */
paths:

  /authentications:
    post:
      summary: Autenticazione utenti
      description: >-
        Autenticazione e ritorno di un codice a 4 cifre come conferma
      responses:
        '200':
          description: 'Registrazione avvenuta con successo'
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: 'Vero se l'autenticazione è avvenuta con successo'
                  token:
                    type: int
                    description: 'JWT token'
        '401':
          description: 'Email o password errati'
      requestBody:
        description: >-
          L'Email e la password devono essere passati nel corpo
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  description: 'Indirizzo email dell'utente'
                password:
                  type: string
                  description: 'Password dell'utente'
            examples:
              example1:
                value:
                  email: 'mario.rossi@unitn.it'
                  password: 'password'
    

  /utente:
    get:
      description: >-
        Ottieni la lista degli utenti.
        E' possibile mostrare gli utenti in base al loro ruolo /utente?ruolo={ruolo}
      summary: Mostra tutti gli utenti
      parameters:
        - in: query
          name: ruolo
          schema:
            type: string
            enum: [turista, pubblica amministrazione]
      responses:
        '200':
          description: 'Insieme di utenti'
          content:
            application/json:
              schema:
                type: array
                items:
       /*           $ref: '#/components/schemas/Utenti'*/
    post:
      description: >-
        Creazione di un nuovo utente nel sistema.
      summary: Registrazione nuovo utente
      requestBody:
        content:
          application/json:
            schema: 
             /* $ref: '#/components/schemas/Utenti'*/
            examples:
              example1:
                value:
                  email: 'mario.rossi@unitn.it'
      responses:
        '201':
          description: 'Utente creato. Link nell'intestazione della posizione'
          headers:
            'Location':
              schema:
                type: string
              description: Link all'utente ceato recentemente.

  /Itineraio:
    get:
      description: >-
        Ottieni la lista di itinerari.
        E' possibile vedere le specifiche dell'itinerario /Itinerario?specifiche={specifiche}
      summary: Mostra tutti gli itinerari
      parameters:
        - in: query
          name: specifiche
          schema:
            type: string
           /* enum: [] */
      responses:
        '200':
          description: 'Insieme di itinerari'
          content:
            application/json:
              schema:
                type: array
                items:
                 /* $ref: '#/components/schemas/Itinerari' */
    post:
      description: >-
        Creates nuovo itinerario.
      summary: Aggiungi itinerario
      requestBody:
        content:
          application/json:
            schema: 
            /*  $ref: '#/components/schemas/Itinerario' */
            examples:
              example1:
                value:
                  title: 'Tour dei musei'
      responses:
        '201':
          description: 'Itinerario creato. Link nell'intestazione Posizione'
          headers:
            'Location':
              schema:
                type: string
              description: Link all'itinerario recentemente creato.
  /books/{bookId}:
    get:
      description: >-
        Ottieni l'itinerario con il nome dato.
      summary: Mostra itinerario
      parameters:
        - in: path
          name: nomeItinerario
          required: true
          schema:
            type: string
          description: 'Nome dell'itinerario'
      responses:
        '200':
          description: 'Itinerario trovato'
          content:
            application/json:
              schema:
             /*   $ref: '#/components/schemas/Itinerario' */
        '404':
          description: 'Itinerario non trovato'

  /booklendings:
    get:
      description: >-
        Gets the list of booklendings.
        It is possible to show booklendings by studentId /booklendings?studentId={student}
      summary: View all booklendings
      security:
        - TokenQueryAuth: []
          XAccessTokenHeaderAuth: []
      parameters:
        - in: query
          name: studentId
          schema:
            type: string
            description: 'ID of the student'
      responses:
        '200':
          description: 'Collection of booklendings'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booklending'
    post:
      summary: Borrow a book
      description: >-
        Creates a new booklending.
        Token must be passed in the header.
        The student and book must already exist in the system.
        The book must be available.
        The book status will be set to 'lended'.
        The booklending will be created with the current date as start date.
        The booklending will be created with the end date set to 30 days from now.
        The booklending will be created with the status 'active'.
      security:
        - TokenQueryAuth: []
          XAccessTokenHeaderAuth: []
      responses:
        '201':
          description: 'Booklending created. Link in the Location header'
          headers:
            'Location':
              schema:
                type: string
              description: Link to the newly created booklending.
      requestBody:
        description: >-
          The booklending object to be created.
          The student and book must already exist in the system.
          The book must be available.
          The book status will be set to 'lended'.
          The booklending will be created with the current date as start date.
          The booklending will be created with the end date set to 30 days from now.
          The booklending will be created with the status 'active'.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Booklending'
            examples:
              example1:
                value:
                  student: 'http://localhost:8080/api/v1/students/1'
                  book: 'http://localhost:8080/api/v1/books/1'
          
components:

  securitySchemes:
    
    XAccessTokenHeaderAuth: # arbitrary name for the security scheme
      description: >-
        The API authentication.
        The API key must be passed in the header 'x-access-token'.
        The API key must be a valid JWT token.
      type: apiKey
      in: header
      name: x-access-token
    
    TokenQueryAuth: # arbitrary name for the security scheme
      description: >-
        The API authentication.
        The API key must be passed in the query string 'token'.
        The API key must be a valid JWT token.
      type: apiKey
      in: query
      name: token

  schemas:

    Student:
      type: object
      required:
        - email
      properties:
        self:
          type: string
          description: 'Link to the student'
        email:
          type: string
          description: 'Email address of the student'
    
    Book:
      type: object
      required:
        - title
        - author
        - ISBN
        - status
      properties:
        self:
          type: string
          description: 'Link to the book'
        title:
          type: string
          description: 'Title of the book'
        author:
          type: string
          description: 'Author of the book'
        ISBN:
          type: string
          description: 'ISBN of the book'
        status:
          type: string
          enum: [available, lended]
          description: 'Tells whether the book is currently available or not'
    
    Booklending:
      type: object
      required:
      - student
      - book
      properties:
        self:
          type: string
          description: 'Link to the booklending'
        student:
          type: string
          description: 'Link to the student'
        book:
          type: string
          description: 'Link to the book'
        start_date:
          type: string
          format: date-time
          description: 'Start date of the booklending'
          default: '${currentDate}'
        end_date:
          type: string
          format: date-time
          description: 'End date of the booklending'
        status:
          type: string
          enum: [active, expired]
          description: 'Tells whether the booklending is currently active or not'
        overdue:  
          type: boolean
          description: >-
            Tells whether the booklending is currently overdue or not.
            The booklending is overdue if the end date is in the past and the status is 'active'.
            The booklending is not overdue if the end date is in the future and the status is 'active'.
            The booklending is not overdue if the status is 'expired'.
        overdue_days:
          type: integer
          description: >-
            Number of days the booklending is overdue.
            The booklending is overdue if the end date is in the past and the status is 'active'.
            The booklending is not overdue if the end date is in the future and the status is 'active'.
            The booklending is not overdue if the status is 'expired'.
            The number of days is calculated as the difference between the current date and the end date.





