openapi: 3.0.4

info:
  version: '1.0'
  title: "Tap-on-places OpenAPI 3.0"
  description: API per i turisti e per il comune di Trento per la gestione di attività, itinerari e informazioni aggregate.
  license:
    name: MIT

servers:
  - url: http://localhost:8080/api/v1
    description: Localhost
  - url: https://TapOnPlaces.onrender.com/api/v1
    description: render.com

security:
  - XAccessTokenHeaderAuth: []

paths:

  /autenticazioni:
    post:
      summary: Autenticazione utenti
      description: Autenticazione utente e ritorno di un token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  description: Indirizzo email dell'utente
                password:
                  type: string
                  description: Password dell'utente
            examples:
              example1:
                value:
                  email: mario.rossi@unitn.it
                  password: password
      responses:
        '200':
          description: Autenticazione avvenuta con successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  token:
                    type: string
                    description: Token JWT
        '401':
          description: Email o password errati

  /utenti:
    get:
      summary: Mostra tutti gli utenti
      description: Ottieni la lista degli utenti, eventualmente filtrata per ruolo.
      parameters:
        - in: query
          name: ruolo
          schema:
            type: string
            enum: [utente_comunale, utente_normale]
      responses:
        '200':
          description: Insieme di utenti
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Utente'

    post:
      summary: Registrazione nuovo utente
      description: Creazione di un nuovo utente nel sistema.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Utente'
      responses:
        '201':
          description: Utente creato con successo
          headers:
            Location:
              description: Link all'utente creato
              schema:
                type: string

  /itinerari:
    get:
      summary: Mostra tutti gli itinerari
      description: Ottieni la lista di itinerari, filtrabili tramite specifiche.
      parameters:
        - in: query
          name: specifiche
          schema:
            type: string
      responses:
        '200':
          description: Insieme di itinerari
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Itinerario'

    post:
      summary: Aggiungi itinerario
      description: Creazione di un nuovo itinerario.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Itinerario'
      responses:
        '201':
          description: Itinerario creato con successo
          headers:
            Location:
              description: Link all'itinerario creato
              schema:
                type: string

  /informazioni:
    get:
      summary: Mostra tutte le informazioni
      description: Restituisce informazioni aggregate su attività e itinerari.
      parameters:
        - in: query
          name: specifiche
          schema:
            type: string
      responses:
        '200':
          description: Insieme di informazioni
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Informazione'

  /informazioni/statistiche-globali:
    get:
      summary: Statistiche globali
      description: Restituisce statistiche aggregate globali per il comune.
      responses:
        '200':
          description: Statistiche globali
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatisticheGlobali'

  /informazioni/attivita/{id}:
    get:
      summary: Informazioni su una specifica attività
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Informazioni attività
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Informazione'
        '404':
          description: Attività non trovata

  /informazioni/itinerario/{id}:
    get:
      summary: Informazioni su un itinerario specifico
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Informazioni itinerario
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Informazione'
        '404':
          description: Itinerario non trovato

components:

  securitySchemes:
    XAccessTokenHeaderAuth:
      type: apiKey
      in: header
      name: x-access-token
      description: Token JWT passato tramite header

  schemas:

    Utente:
      type: object
      required:
        - nome
        - cognome
        - email
      properties:
        self:
          type: string
        nome:
          type: string
        cognome:
          type: string
        email:
          type: string

    Itinerario:
      type: object
      required:
        - titolo
        - tempo
        - tipologia
        - budget
      properties:
        self:
          type: string
        titolo:
          type: string
        tempo:
          type: string
        tipologia:
          type: string
        budget:
          type: integer

    Informazione:
      type: object
      required:
        - self
        - tipo
        - nome
        - numPersone
        - etMedia
        - orario
      properties:
        self:
          type: string
        tipo:
          type: string
          enum: [attivita, itinerario]
        nome:
          type: string
        tipologia:
          type: string
        tempo:
          type: string
        budget:
          type: integer
        numPersone:
          type: integer
        etMedia:
          type: integer
        orario:
          type: string

    StatisticheGlobali:
      type: object
      properties:
        totalUsers:
          type: integer
        totalItineraries:
          type: integer
        totalActivities:
          type: integer
        totalFavorites:
          type: integer
        etMediaUtenti:
          type: integer
        topAttivita:
          type: array
          items:
            type: object
            properties:
              nome:
                type: string
              tipo:
                type: string
              visite:
                type: integer
        topItinerari:
          type: array
          items:
            type: object
            properties:
              nome:
                type: string
              tipologia:
                type: string
              visite:
                type: integer

      
