openapi: 3.0.4
info:
  version: '1.0'
  title: "Tap-on-places OpenAPI 3.0"
  description: API per i turisti per trovare le attività di Trento.
  license:
    name: MIT
servers:
  - url: http://localhost:8080/api/v1
    description: Localhost
  - url: https://TapOnPlaces.onrender.com/api/v1
    description: render.com
    
paths:

  /autenticazioni:
    post:
      summary: Autenticazione utenti
      description: >-
        Autenticazione e ritorno di un codice a 4 cifre come conferma
      responses:
        '200':
          description: 'Registrazione avvenuta con successo'
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: 'Vero se l\'autenticazione è avvenuta con successo'
                  token:
                    type: string
                    description: 'Codice a 4 cifre per conferma autenticazione'
        '401':
          description: 'Email o password errati'
      requestBody:
        description: >-
          L\'Email e la password devono essere passati nel corpo
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  description: 'Indirizzo email dell\'utente'
                password:
                  type: string
                  description: 'Password dell\'utente'
            examples:
              example1:
                value:
                  email: 'mario.rossi@unitn.it'
                  password: 'password'
    

  /utenti:
    get:
      description: >-
        Ottieni la lista degli utenti.
        è possibile mostrare gli utenti in base al loro ruolo /utente?ruolo={ruolo}
      summary: Mostra tutti gli utenti
      parameters:
        - in: query
          name: ruolo
          schema:
            type: string
            enum: [utente_comunale, utente_normale]
      responses:
        '200':
          description: 'Insieme di utenti'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Utente'
    post:
      description: >-
        Creazione di un nuovo utente nel sistema.
      summary: Registrazione nuovo utente
      requestBody:
        content:
          application/json:
            schema: 
                $ref: '#/components/schemas/Utente'
            examples:
              example1:
                value:
                  email: 'mario.rossi@unitn.it'
      responses:
        '201':
          description: 'Utente creato. Link nell\'intestazione della posizione'
          headers:
            'Location':
              schema:
                type: string
              description: Link all\'utente creato recentemente.

  /itinerari:
    get:
      description: >-
        Ottieni la lista di itinerari.
        è possibile vedere le specifiche dell\'itinerario /Itinerario?specifiche={specifiche}
      summary: Mostra tutti gli itinerari
      parameters:
        - in: query
          name: specifiche
          schema:
            type: string
      responses:
        '200':
          description: 'Insieme di itinerari'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Itinerario' 
    post:
      description: >-
        Creare nuovo itinerario.
      summary: Aggiungi itinerario
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Itinerario' 
            examples:
              example1:
                value:
                  title: 'Tour dei musei'
      responses:
        '201':
          description: 'Itinerario creato. Link nell\'intestazione Posizione'
          headers:
            'Location':
              schema:
                type: string
              description: Link all\'itinerario recentemente creato.
  /attività/{nomeAttività}:
    get:
      description: >-
        Ottieni l\'attività con il nome dato.
      summary: Mostra attività
      parameters:
        - in: path
          name: nomeAttività
          required: true
          schema:
            type: string
          description: 'Nome dell\'attività'
      responses:
        '200':
          description: 'Attività trovata'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Attività' 
        '404':
          description: 'Attività non trovata'

  /informazioni:
    get:
      description: >-
        Ottieni la lista di informazioni.
      summary: Mostra tutte le informazioni
      parameters:
        - in: query
          name: specifiche
          schema:
            type: string
      responses:
        '200':
          description: 'Insieme di informazioni'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Informazione' 
    
/api:
  get:
    security:
      - TokenQueryAuth: []
      XAccessTokenHeaderAuth: []
  
  
components:

  securitySchemes:
    
    XAccessTokenHeaderAuth: # arbitrary name for the security scheme
      description: >-
        The API authentication.
        The API key must be passed in the header 'x-access-token'.
        The API key must be a valid JWT token.
      type: apiKey
      in: header
      name: x-access-token
    
    TokenQueryAuth: # arbitrary name for the security scheme
      description: >-
        The API authentication.
        The API key must be passed in the query string 'token'.
        The API key must be a valid JWT token.
      type: apiKey
      in: query
      name: token

  schemas:

    Utente:
      type: object
      required:
        - nome
        - cognome
        - email
      properties:
        self:
          type: string
          description: 'Link all\'utente'
        nome:
          type: string
          description: 'Nome dell\'utente'
        cognome:
          type: string
          description: 'Cognome dell\'utente'
        email:
          type: string
          description: 'Indirizzo Email dell\'utente'
    
    Itinerario:
      type: object
      required:
        - titolo
        - tempo
        - tipologia
        - budget
      properties:
        self:
          type: string
          description: 'Link all\'itinerario'
        titolo:
          type: string
          description: 'Titolo dell\'itinerario'
        tempo:
          type: string
          description: 'Tempo dell\'itinerario'
        tipologia:
          type: string
          description: 'Tipologia dell\'itinerario'
        budget:
          type: integer
          description: 'Budget disponibile per l\'itinerario'

    Attività:
      type: object
      required:
        - nome
      properties:
        self:
          type: string
          description: 'Link all\'attività'
        nome:
          type: string
          description: 'nome dell\'attività'
        numPersone:
          type: integer
          description: 'Numero di volte che questa attività è stata cercata dagli utenti'

    Informazione:
      type: object
      required:
        - numPersone
        - etàMedia
        - orario
      properties:
        self:
          type: string
          description: 'Link all\'informazione'
        numPersone:
          type: integer
          description: 'Numero di volte che questa attività è stata cercata dagli utenti'
        etàMedia:
          type: integer
          description: 'Età media dei visitanti'
        orario:
          type: string
          description: 'Orari più richiesti'
      
